### ISSUE TITLE
Allow the maven-plugin to take multiple arguments on the command line

### ISSUE THREAD

**Issue by torbjornvatn** [cucumber-attic/cuke4duke#14]
@feature request
The current version of the plugin supports a single argument through the parameter <code>-Dcucumber.args=VALUE</code>

This can be somewhat limiting, and I propose something like syntax used by the maven-scala-plugin <code>-DaddArgs=arg1|arg2|arg3</code>

This will require parsing of the arguments by the pipe character.

**Comment by aslakhellesoy** [comment]
Have a go at it Torbjørn!

**Comment by aslakhellesoy** [comment]
I have left some line comments in [your commit](http://github.com/torbjornvatn/cuke4duke/commit/9056fbe5ecb572c1c32d350952eed38522bfda7c). Please don't lump unrelated changes together in one commit. Also - please add an entry to History.txt. An undocumented feature is a non-feature ;-)

Otherwise great work.

**Comment by aslakhellesoy** [comment]
Why use colon instead of bar (scala plugin)?

**Comment by torbjornvatn** [comment]
Tried using the bar but it caused my linux terminal to use the pipe command, naturally. So I went with the colon instead.

**Comment by aslakhellesoy** [comment]
Doh. Makes sense that the bar would be caught by the shell. However, colon is problematic too. Cucumber's --tags switch can be used like this: --tags @dev:3 (to limit WIP)

Wouldn't it be better if we could use spaces, and just quote everything?
