### ISSUE TITLE
DRYer pom.xml files

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#19]
The parent POM, cuke4duke POM and various example POMs have a fair bit of duplication. We should try to reduce some of this duplication - especially:
- versions
- scope

At the same time, we should be explicit about versions, but in as few places as possible. Not sure how to do this (don't understand maven well enough).

**Comment by fabianbuch** [comment]
You can set e.g. properties like this:

```
<properties>
    <springVersion>3.0.0.M4</springVersion>
    <springSecurityVersion>3.0.0.M1</springSecurityVersion>
    <junit.version>4.6</junit.version>
    <jetty.version>6.1.20</jetty.version>
</properties>
```

And use them in your dependencies: ${springVersion}

**Comment by teigen** [comment]
in addition to a properties section for reused version numbers, all dependencies could be listed in a "dependencymanagement" section in the parent pom. Then all child poms could reference the dependency without the need of a version tag.
You can also do the same for plugins with a pluginManagement section in the parent pom.

for more information, see http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by aslakhellesoy** [comment]
Thanks for the tips. If anyone wants to submit a patch, please make sure each example's POM doesn't have any dependencies on other POMs - as I think this would make it a little harder for people to just copy and paste them into their own projects.

**Comment by aslakhellesoy** [comment]
Note to self - I saw someone mentioned the versions plugin - might be worth looking into too.

**Comment by darrinholst** [comment]
My fork has some refactorings that you may be interested in. The master branch has just a few changes to the main and maven plugin pom...moving compiler settings up to the parent, removing redundant information that was inherited from the parent, etc.

I have another branch called example_pom_rework that has some pretty aggressive changes that you may or may not want. You said that you don't want any of the example poms referencing any other pom, but that's kind of hard to do with the current version of maven (maven 3 is supposed to have support for mixins). So I defiantly added an examples parent pom since I don't know of any other way to dry the poms up. I moved repository info, dependency management, and compiler settings up to this parent. I also cleaned up a lot of unused dependencies in each of the example projects.

**Comment by aslakhellesoy** [comment]
Darrin,

I took a look at your example_pom_rework branch. While this reduces duplication I also think it makes it more difficult for people to get started with cuke4duke. With your changes they have to copy and paste XML from two POMs, even though their own project might not use inheritance.

So I'm not convinced about merging this in. Thoughts?

**Comment by darrinholst** [comment]
Yeah, that's what I thought too. So the example poms will have to be a little moist for ease of getting started.

**Comment by aslakhellesoy** [comment]
Ok, closing this now. Things did get better in the non-example POMs. Thanks!
