### ISSUE TITLE
Look at class, not instance to detect scala step definitions.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/cuke4duke#21]
I have added an explanation of why in the code. See this commit: 20321f017f8d3a6a41ee71fc2f1766fffebb93f4

**Comment by aslakhellesoy** [comment]
Maybe the Given/When/Then methods could store the step definitions in a static Map<Class, List<ScalaStepDefinition>> somewhere. Then ScalaAnalyzer.registerHooksAndStepDefinitionsFor(...) could look them up in that Map later. Maybe not the most elegant solution, but maybe it can be done cleaner in Scala than in Java.

**Comment by aslakhellesoy** [comment]
Another option could be to make ClassLanguage a singleton (with a getInstance() method - yuck) and register the step definitions directly on that singleton from within the Given/When/Then methods. If you go for that approach, the registerHooksAndStepDefinitionsFor(...) method could be empty and do nothing (it would already be done in the Given/When/Then methods).

**Comment by teigen** [comment]
(Aslak: Edited formatting of list)

This one is a little tricky.
Scala step definitions are really just closures paired with a string, so doing this through static analysis would not work. Storing stepdefinitions in a singleton would not be correct since the stepdefinitions would then be referencing the world they were created in.

What we can do, is capture the stepdefinitions for each new world being created. That would correctly scope the closures to the world defined by the objectfactory (since the objectfactory should be used to create the instances of the scalaDsl).

The result would then be pretty good where all tests are run in the same classloader allowing caching of expensive stuff in singletons, while at the same time executing the defined world.

The process would then be
- pass all classfiles to cuke4duke
- create objectfactory
- repeat:
  - create world
  - capture stepdefinitions
  - execute
  - dispose world

Alternatively we could capture the stepdefinitions in a "dry run", an return delegators for each stepdefinition. The delegators would the execute the re-captured ones scoped to the correct world. This could give some strange behaviour if people have sideeffects in their ScalaDsl constructors (they would get n+1 applications of that effect)

**Comment by aslakhellesoy** [comment]
Fixed a few weeks back during a heroic hacking session
