### ISSUE TITLE
Commit 4b6129ea94445424ad0b7ad51657ff8c9a8cb332

### ISSUE THREAD

**Issue by oferrigni** [cucumber-attic/cuke4duke#65]
Breaks the build.xml in examples/java.  Fresh checkout today, first time using cuke4duke.  Rolled back to v0.2.3 fixed problem.  Error from build follows:

-compile-steps:
    [javac] Compiling 8 source files to cuke4duke/examples/java/target/test-classes
    [javac] cuke4duke/examples/java/src/test/java/simple/HalfManualSteps.java:15: cannot find symbol
    [javac] symbol  : method ask(java.lang.String,int)
    [javac] location: class simple.HalfManualSteps
    [javac]             String answer = ask("Here is a question for you. Wait 5 secs to make it pass. Type a string and hit enter to fail.", 5);
    [javac]                             ^
    [javac] cuke4duke/examples/java/src/test/java/simple/StuffSteps.java:77: cannot find symbol
    [javac] symbol  : class CellConverter
    [javac] location: class simple.StuffSteps
    [javac]         t.mapColumn("b", new CellConverter() {
    [javac]                              ^
    [javac] cuke4duke/examples/java/src/test/java/simple/StuffSteps.java:82: cannot find symbol
    [javac] symbol  : method mapHeaders(<anonymous java.util.HashMap<java.lang.Object,java.lang.String>>)
    [javac] location: interface cuke4duke.Table
    [javac]         t.mapHeaders(new HashMap<Object, String>() {{
    [javac]          ^
    [javac] 3 errors

Thanks.

**Comment by aslakhellesoy** [comment]
Have you followed the build instructions?
http://wiki.github.com/aslakhellesoy/cuke4duke/build-cuke4duke

**Comment by aslakhellesoy** [comment]
The problem here is that you need to tell Ant to use cucumber master. That can be done by passing bin="..." to the cucumber task. You also have to modify the classpaths to point to the cucumber jar built from source. Previously released cuke4duke jars won't work, because there are changes since the last release. (The compile errors you're seeing won't happen against a source build).

I have verified that it works by modifying build.xml, but I didn't commit my changes to build.xml because it is intended to be copied by other people.

**Comment by oferrigni** [comment]
Will check it out.  Thank you for clearing this up.

**Comment by aslakhellesoy** [comment]
Works for me with cucumber from master.
