### ISSUE TITLE
Make the Cuke4Duke Plugin Honor the -Dmaven.test.skip.exec=true

### ISSUE THREAD

**Issue by roloreaper** [cucumber-attic/cuke4duke#73]
At current their is no way to skip Running Cuke 4 Duke!

**Comment by aslakhellesoy** [comment]
Are you going to write a patch?

**Comment by aslakhellesoy** [comment]
Isn't it <code>-DskipITs=true</code> that's supposed to skip integration tests? http://maven.apache.org/plugins/maven-failsafe-plugin/integration-test-mojo.html#skipITs

**Comment by roloreaper** [comment]
Will check if I can check the Code out. also will look at the <code>-DskipITS=true</code> as a workarround

**Comment by nealeu** [comment]
For clarity, I think the behaviour should be that -Dmaven.test.skip=true  should skip running the features, as this has already skipped compiling the tests, so you've no fixtures to run against.

Additionally, the plugin could have a <skip> element in it's configuration (as other plugins have).  This would allow profile based skipping.  Honouring -DskipITs would be less of an issue.  If you wanted to skip running features, then I'd suggest not overlapping with someone elses defs, and instead being explicit by supporting -DskipFeatures, although this is a moot point if you (or I ;-) implement <skip> in the configuration.

**Comment by nealeu** [comment]
It turned out that "I" was the answer.  I've just pushed changes to my fork which gives the following behaviour:
- Skipping features will result in the plugin skipping running features (but after the installGems stage, as I thought this might be a useful combo to allow), and instead you'll see:  "[INFO] Cucumber Features are skipped"
- Skipping of tests is triggered by the the <skip> config parameter, which defaults to maven.test.skip.
- To skip only features, this can be overridden by adding the following 
  <configuration>
    <skip>${skipFeatures}</skip>
  </configuration>
  assuming you wanted to have -DskipFeatures=true to skip your features.

**Comment by aslakhellesoy** [comment]
Attributions. Closed by a5900489e830c4d30a1b701e1cb9e2af4a6deb79. Closed by a5900489e830c4d30a1b701e1cb9e2af4a6deb79.

**Comment by roloreaper** [comment]
Thanks its cool :)
